theme: jekyll-theme-tactile
title: [L impact d'un événement financier sur le bonheur d une population]
description: [Projet réalisé par Colin Parent%2C Victor Papin&#x2C; Ines Rahaoui&#44; Younes Lazar en L1S2 à Sorbonne Université]
