theme: jekyll-theme-tactile
title: [L impact d'un événement financier sur le bonheur d une population]
description: [Projet réalisé par Colin Parent, Victor Papin, Ines Rahaoui, Younes Lazar en L1S2 à Sorbonne Université]
